/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as InstitutionSlugIndexRouteImport } from "./app/$institution.$slug/index";
import { Route as rootRouteImport } from "./app/__root";
import { Route as IndexRouteImport } from "./app/index";

const IndexRoute = IndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRouteImport,
} as any);
const InstitutionSlugIndexRoute = InstitutionSlugIndexRouteImport.update({
	id: "/$institution/$slug/",
	path: "/$institution/$slug/",
	getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute;
	"/$institution/$slug": typeof InstitutionSlugIndexRoute;
}
export interface FileRoutesByTo {
	"/": typeof IndexRoute;
	"/$institution/$slug": typeof InstitutionSlugIndexRoute;
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport;
	"/": typeof IndexRoute;
	"/$institution/$slug/": typeof InstitutionSlugIndexRoute;
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths: "/" | "/$institution/$slug";
	fileRoutesByTo: FileRoutesByTo;
	to: "/" | "/$institution/$slug";
	id: "__root__" | "/" | "/$institution/$slug/";
	fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	InstitutionSlugIndexRoute: typeof InstitutionSlugIndexRoute;
}

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/$institution/$slug/": {
			id: "/$institution/$slug/";
			path: "/$institution/$slug";
			fullPath: "/$institution/$slug";
			preLoaderRoute: typeof InstitutionSlugIndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
	}
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	InstitutionSlugIndexRoute: InstitutionSlugIndexRoute,
};
export const routeTree = rootRouteImport
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

import type { createStart } from "@tanstack/react-start";
import type { getRouter } from "./router.tsx";
declare module "@tanstack/react-start" {
	interface Register {
		ssr: true;
		router: Awaited<ReturnType<typeof getRouter>>;
	}
}
